### ISSUE TITLE
Can not have custom props

### ISSUE THREAD

**Issue by ieschalier** [didierfranc/react-sc#2]
<img width="857" alt="screen shot 2017-05-26 at 15 20 31" src="https://cloud.githubusercontent.com/assets/2832910/26496225/ec7aad62-4226-11e7-8d10-b4a44595115a.png">

**Comment by didierfranc** [comment]
We should be able to avoid [styled-components whitelist](https://github.com/styled-components/styled-components/blob/v2.0.0/src/utils/validAttr.js) using `is` attribute
